#### Import NumPy 

In [ ]:
import numpy as np

#### Create an array of 10 zeros 

In [ ]:
array=np.zeros(10)
array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Create an array of 10 ones

In [ ]:
array=np.ones(10)
array

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Create an array of 10 fives

In [ ]:
array=np.ones(10)*5
array

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### Create an array of the integers from 10 to 50 -!del!-

In [ ]:
array=np.arange(10,51)
array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Create an array of all the even integers from 10 to 50  -!del!-

In [ ]:
array=np.arange(10,51,2)
array

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### Create a 3x3 matrix with values ranging from 0 to 8

In [ ]:
array=np.arange(0,9).reshape(3,3)

#### Create a 3x3 identity matrix

In [ ]:
array=np.eye(3,3)  # or np.identity(3)
array

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Use NumPy to generate a random number between 0 and 1  -!del!-

In [ ]:
from numpy import random
n=random.rand()
n

0.39398598768999304

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [ ]:
array=np.random.normal(size=25) #or for different paramenters: np.random.normal(0,1,25)
array

array([-0.04041102,  2.52419757,  0.22858748, -0.17714647,  1.56423226,
        0.66247439,  1.47700556,  0.09744235, -0.0715604 , -0.66460837,
        0.0333644 ,  0.39155091, -0.06202291,  0.64757147, -2.04293587,
        1.48399692, -1.44040386,  0.67698804,  0.03215598,  0.2695801 ,
       -0.20349494,  0.47918444, -0.30619577,  0.49661767, -0.079974  ])

#### Create the following matrix: -!del!-

In [ ]:
array=np.arange(0.01,1.01,0.01).reshape(10,10)
array

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

#### Create an array of 20 linearly spaced points between 0 and 1: 

In [ ]:
array=np.linspace(0,1,20)
array

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [ ]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

t=np.arange(11,26)
array=np.delete(t,np.arange(0,t.size,5)).reshape(3,4)
array

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE
print(20)

20


20

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE
array=np.arange(2,13,5).reshape(3,1)
array

array([[ 2],
       [ 7],
       [12]])

array([[ 2],
       [ 7],
       [12]])

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE
array=np.arange(21,26)
array

array([21, 22, 23, 24, 25])

array([21, 22, 23, 24, 25])

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE
array=np.arange(16,26).reshape(2,5)
array

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Now do the following

#### Get the sum of all the values in mat

In [ ]:
np.sum(mat)

325

#### Get the standard deviation of the values in mat

In [ ]:
np.std(mat)

7.211102550927978

#### Get the sum of all the columns in mat

In [ ]:
np.sum(mat,axis=0)

array([55, 60, 65, 70, 75])

#### Multiply two matrices using NumPy.

A = [[1, 2], [2, 3]]

B = [[4, 5], [6, 7]]

So, A.B = [[1*4 + 2*6, 2*4 + 3*6], [1*5 + 2*7, 2*5 + 3*7]

The computed answer will be: [[16, 26], [19, 31]]


In [ ]:
A = [[1, 2], [2, 3]]
B = [[4, 5], [6, 7]]
np.dot(A,B)

array([[16, 19],
       [26, 31]])

####Replace NaN values with average of that column

Initial array :  

[[ 1.3  2.5  3.6  nan]
 [ 2.6  3.3  nan  5.5]
 [ 2.1  3.2  5.4  6.5]]


In [ ]:
iarray = np.array([[1.3, 2.5, 3.6, np.nan],[2.6, 3.3, np.nan, 5.5],[2.1, 3.2, 5.4, 6.5]])

avg = np.nanmean(iarray, axis = 0) #calculates average for each column

indices = np.where(np.isnan(iarray)) #stores all indices where null values are present
iarray[indices] = np.take(avg,indices[1]) #for all those indices, replaces with avg
iarray

array([[1.3, 2.5, 3.6, 6. ],
       [2.6, 3.3, 4.5, 5.5],
       [2.1, 3.2, 5.4, 6.5]])

# You're done!

In [ ]:
import pandas as pd
df=pd.read_csv('data.csv')
df.head()
#gives first 5 rows if nothing is mentioned

Unnamed: 0  acousticness  danceability  duration_ms  energy  \
0           0        0.0102         0.833       204600   0.434   
1           1        0.1990         0.743       326933   0.359   
2           2        0.0344         0.838       185707   0.412   
3           3        0.6040         0.494       199413   0.338   
4           4        0.1800         0.678       392893   0.561   

   instrumentalness  key  liveness  loudness  mode  speechiness    tempo  \
0          0.021900    2    0.1650    -8.795     1       0.4310  150.062   
1          0.006110    1    0.1370   -10.401     1       0.0794  160.083   
2          0.000234    2    0.1590    -7.148     1       0.2890   75.044   
3          0.510000    5    0.0922   -15.236     1       0.0261   86.468   
4          0.512000    5    0.4390   -11.648     0       0.0694  174.004   

   time_signature  valence  target      song_title            artist  
0             4.0    0.286       1        Mask Off            Future  
1             4.0    0.588       1         Redbone  Childish Gambino  
2             4.0    0.173       1    Xanny Family            Future  
3             4.0    0.230       1  Master Of None       Beach House  
4             4.0    0.904       1  Parallel Lines       Junior Boys

In [ ]:
#Find songs with value for energy column greater than 0.4 and display values for song_title column.
df[df['energy']>0.4]['song_title']
# inner df[] accesses column values, outer df[]['song_title'] gives all the rows where the value satisfies the condition

0                                   Mask Off
2                               Xanny Family
4                             Parallel Lines
5                                   Sneakin’
6                                Childs Play
                        ...                 
2012     Like A Bitch - Kill The Noise Remix
2013                                   Candy
2014    Habit - Dack Janiels & Wenzday Remix
2015                           First Contact
2016                      I Wanna Get Better
Name: song_title, Length: 1830, dtype: object

In [ ]:
#For songs with duration duration_ms value less than 300000 ms (300 s), find Top 10 “fastest” songs( songs with highest values for tempo column ) and display values for song_title, artistcolumns.
df1 = df[df['duration_ms'] < 300000]
#filter the rest of rows
df2 = df1.sort_values('tempo',ascending=False)[['song_title', 'artist','tempo']].head(10)
#sort the new data frame in descending order and pick first 10 as required, displaying only what is asked
df2

song_title            artist    tempo
124       Danger and Dread        Brown Bird  209.686
718            Hannah Hunt   Vampire Weekend  207.969
1960            Puppy Love      Donny Osmond  203.822
1711               Amazing     Big Time Rush  202.013
809        Tupelo - Part 1       Pop Staples  200.749
826     Living Every Dream            Antwon  200.035
1339  The Shaping Sickness  Shadow of Intent  199.988
102         Willing & Able        Disclosure  199.727
1802             Mad Love.              JoJo  199.519
532        Wake Bake Skate            FIDLAR  198.040

In [ ]:
df[(df['artist']=='Drake') & (df['energy']>0.5)]['song_title']
#multiple conditions can be included using &

5                      Sneakin’
37                      Jumpman
117               Hotline Bling
154                   Big Rings
440                   Headlines
589     Started From the Bottom
779     0 To 100 / The Catch Up
1016           Skepta Interlude
1218            Best I Ever Had
1223                  Take Care
Name: song_title, dtype: object

In [ ]:
#top 10 for the instrumentalness metric, this dataframe should only contain the instrumentalness, song title and artist columns.
df.sort_values('instrumentalness', ascending=False)[['song_title','artist']].head(10)

song_title                    artist
1313                       Senseless Order        Signs of the Swarm
271   So Destroyed (channeling Rage Peace)               Prince Rama
1575             A Hundred Dreams from Now                Ray Bryant
1619                                 Raven             John Dahlbäck
725                      Strandbar (disko)                Todd Terje
1546                        Almas vaggvisa         Jan Lundgren Trio
1322                            Pitchblack  Walking Dead On Broadway
1349                       Prismatic Abyss           Aversions Crown
1661                               Yebisah               Mark Knight
121                         Chasing Heaven                Bassnectar

In [ ]:
#dataframe of the average tempo for each of the top 10 most occurring artists.

df1=df['artist'].value_counts().index.tolist()[:10]
print(df1)
#count number of times each artist has occured using value_counts
#index.tolist converts it to a list
#[:10] picks first 10 values(most occuring artists) from the list

df2=df.loc[df['artist'].isin(df1)] #filter out all rows that aren't of the top 10 artists

#loc accesses a group of rows and columns by labels
#is in is used to check if each element in the DataFrame(artist col) is contained in df1

df3=df2.groupby('artist').mean('tempo')
#doubt:my understanding is: mean('tempo') will only calculate mean of tempo, not any other col after grouping,
#but when I don't write anything in () it makes no difference for other parameters

#group the filtered data frame containing only top 10 artists' rows and fill their average
df4=df3[['tempo']]

df4


['Drake', 'Rick Ross', 'Disclosure', 'WALK THE MOON', 'Backstreet Boys', 'Crystal Castles', 'FIDLAR', 'Future', 'Fall Out Boy', 'Skrillex']


tempo
artist                     
Backstreet Boys  113.066600
Crystal Castles  128.600778
Disclosure       128.118417
Drake            112.406750
FIDLAR           145.983444
Fall Out Boy     133.815625
Future           128.989625
Rick Ross        110.721923
Skrillex         132.454125
WALK THE MOON    136.163600